#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci batch <<-EOF
		set luci.themes.Dlinkrouter=/luci-static/dlinkrouter
		set luci.main.mediaurlbase=/luci-static/dlinkrouter
		commit luci
	EOF
fi

exit 0
